---
- name: Update Cache
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Add required packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - ansible
    - texinfo
    - apt-transport-https
    - vim
    - sshpass
    - chrony
